use crate::{
    format,
    model::{CleanupCandidate, CleanupCategory, CleanupRisk, ExecutionKind, ScannerResult},
    scan::{fs_stats, ScanContext, Scanner},
};
use std::time::Instant;

pub struct AppCacheScanner;

impl Scanner for AppCacheScanner {
    fn name(&self) -> &'static str {
        "Browser & Application Caches"
    }

    fn scan(&self, ctx: &ScanContext) -> ScannerResult {
        let started = Instant::now();
        let mut result = ScannerResult {
            module: self.name().into(),
            ..Default::default()
        };

        let app_targets = [
            ("Firefox cache", ".cache/mozilla/firefox", CleanupRisk::Safe),
            (
                "Google Chrome cache",
                ".cache/google-chrome",
                CleanupRisk::Safe,
            ),
            (
                "Brave Browser cache",
                ".cache/BraveSoftware",
                CleanupRisk::Safe,
            ),
            ("Chromium cache", ".cache/chromium", CleanupRisk::Safe),
            ("Spotify cache", ".cache/spotify", CleanupRisk::Safe),
            (
                "Telegram Desktop cache",
                ".cache/TelegramDesktop",
                CleanupRisk::Safe,
            ),
            ("Discord cache", ".cache/discord", CleanupRisk::Safe),
            ("VS Code cache", ".cache/Code", CleanupRisk::Safe),
        ];

        for (title, rel_path, risk) in app_targets {
            if ctx.is_cancelled() {
                break;
            }
            let path = ctx.home.join(rel_path);
            if !path.exists() {
                continue;
            }

            let stats = fs_stats::measure(&path, ctx);
            result.files_scanned += stats.files;
            result.directories_scanned += stats.directories;

            if stats.bytes > 0 {
                result.candidates.push(CleanupCandidate {
                    id: format!("app-cache:{}", rel_path.replace('/', "-")),
                    category: CleanupCategory::UserCache,
                    title: title.to_string(),
                    description: format!("Cache storage generated by {title} ({})", format::bytes(stats.bytes)),
                    path: Some(path),
                    size_bytes: stats.bytes,
                    risk,
                    reason: format!("{title} will recreate needed temporary cache files when launched."),
                    consequence: "Temporary web/media cache is cleared; subsequent application startup or media loading may download data again.".into(),
                    requires_privilege: false,
                    execution: ExecutionKind::UserAllowedDirectory,
                    privileged_action: None,
                });
            }
        }

        result
            .candidates
            .sort_by_key(|c| std::cmp::Reverse(c.size_bytes));
        result.duration_ms = started.elapsed().as_millis();
        result
    }
}
