use crate::{
    model::{CleanupCandidate, CleanupCategory, CleanupRisk, ExecutionKind, ScannerResult},
    scan::{fs_stats, ScanContext, Scanner},
};
use std::time;

pub struct ThumbnailScanner;

impl Scanner for ThumbnailScanner {
    fn name(&self) -> &'static str {
        "Thumbnail cache"
    }

    fn scan(&self, ctx: &ScanContext) -> ScannerResult {
        let started = time::Instant::now();
        let path = ctx.home.join(".cache/thumbnails");
        let mut result = ScannerResult {
            module: self.name().into(),
            ..Default::default()
        };
        if !path.exists() {
            result.duration_ms = started.elapsed().as_millis();
            return result;
        }
        let stats = fs_stats::measure(&path, ctx);
        result.files_scanned = stats.files;
        result.directories_scanned = stats.directories;
        if stats.errors > 0 {
            result.warnings.push(format!(
                "Thumbnail cache measurement encountered {} filesystem error(s); the displayed size may be an undercount.",
                stats.errors
            ));
        }
        if stats.bytes > 0 {
            result.candidates.push(CleanupCandidate {
                id: "thumbnail-cache".into(),
                category: CleanupCategory::ThumbnailCache,
                title: "Thumbnail cache".into(),
                description: "Preview images generated by GNOME and desktop applications.".into(),
                path: Some(path),
                size_bytes: stats.bytes,
                risk: CleanupRisk::Safe,
                reason: "Thumbnails are generated copies and can be recreated when needed.".into(),
                consequence: "Folders with many images may show previews more slowly until thumbnails are rebuilt.".into(),
                requires_privilege: false,
                execution: ExecutionKind::UserAllowedDirectory,
                privileged_action: None,
            });
        }
        result.duration_ms = started.elapsed().as_millis();
        result
    }
}
